### PR TITLE
1.19.2 Port

### PR DESCRIPTION
**Pull request by Devocity**
Made a pretty functional port, only thing that seems broken for now is the ability to camo portal blocks. 

Will update this PR if I manage improvements on my own fork.

### CODE REVIEW

**Comment by Devocity** [comment]
Fixed the camo problem & that render players is not on by default even though it says so in the GUI

**Comment by Seris02** [comment]
👀 

thanks

dealing with life and apathy and much stuff right now, likely wouldn’t have gotten to it (ever)

will do some testing and merge to the master if it works, make a new branch for the old version

**Comment by Devocity** [comment]
No problem! Will also attempt 1.19.4 and 1.20 if it comes out.

**Comment by Seris02** [comment]
merged, and given credit in the mod description for porting, thank you again :>

**Pull request merged**
